In [30]:
import numpy as np
import pandas as pd
import os
import random

In [31]:
input_path = '../datasets/'
target_category = [38, 110, 113, 114, 134, 171, 172, 173, 376, 435, 467, 537, 539, 629, 768]
target_category_str = [str(col) for col in target_category]

In [32]:
log_df = pd.read_csv(os.path.join(input_path, 'carlog.csv'))
meta_df = pd.read_csv(os.path.join(input_path, 'meta.csv'), parse_dates=['date'])
test_df = pd.read_csv(os.path.join(input_path, 'test.csv'))
product_master_df = pd.read_csv(os.path.join(input_path, 'product_master.csv'))
user_master_df = pd.read_csv(os.path.join(input_path, 'user_master.csv'))
sample_submission_df = pd.read_csv(os.path.join(input_path, 'atmaCup#9__sample_submission.csv'))

train_Y = pd.read_csv('../output/train_Y.csv')
test_Y = pd.read_csv('../output/test_Y.csv')

In [23]:
train_Y[train_Y['768']==1].sample(10)

,session_id,38,110,113,114,134,171,172,173,376,435,467,537,539,629,768
377658,628530,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
165156,327546,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
225865,423162,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
172202,339123,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
334908,574175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
168039,332521,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
363579,610682,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
219940,414008,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
238012,441072,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
292099,518471,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [28]:
session_id= 518471

user_id = meta_df[meta_df.session_id==session_id].user_id.values[0]
display(user_master_df[user_master_df.user_id==user_id])
display(train_Y[train_Y['session_id']==session_id])

                     user_id   age  gender
9260  CTWjtkBC9a4BTbxHMLGpND  40.0     1.0

,session_id,38,110,113,114,134,171,172,173,376,435,467,537,539,629,768
292099,518471,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [29]:
cols = ['session_id', 'date', 'hour', 'spend_time', 'name_1', 'kind_1', 'number_1', 'unit_price', 'n_items', 'category_name', 'category_id', 'is_payment' , 'JAN']
log_df2[cols][log_df2['session_id']==session_id]

,session_id,date,hour,spend_time,name_1,kind_1,number_1,unit_price,n_items,category_name,category_id,is_payment,JAN
10958667,518471,2020-03-17,15,0,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN
10958668,518471,2020-03-17,15,15,キレイキレイ泡ハンドソー,商品,1.0,239.0,1,洗面浴用用品__石鹸・ハンド,559.0,0,4903301241010
10958669,518471,2020-03-17,15,121,キッチンタオル,商品,1.0,139.0,1,ペーパー__キッチンペーパー,202.0,0,6970747940362
10958670,518471,2020-03-17,15,133,ﾅﾁｭﾗさら肌さらり吸水ﾅﾌﾟｷﾝ,商品,1.0,375.0,1,衛生__生理用品,660.0,0,4902011789034
10958671,518471,2020-03-17,15,171,マミーポコパンツ ドラえ,商品,1.0,1379.0,1,衛生__子供オムツ,659.0,0,4903111232499
10958672,518471,2020-03-17,15,272,お芋のモーニング,商品,1.0,139.0,1,ホールセールパン__食卓パン(ホールセールパン),210.0,0,4951595682019
10958673,518471,2020-03-17,15,288,北海道練乳ホワイト,商品,1.0,149.0,1,ホールセールパン__食卓パン(ホールセールパン),210.0,0,4951595697341
10958674,518471,2020-03-17,15,325,おかめ仕立てミニ,商品,1.0,79.0,1,和日配__納豆,368.0,0,4901160010044
10958675,518471,2020-03-17,15,325,おかめ仕立てミニ,クーポン,NaN,NaN,0,NaN,NaN,0,NaN
10958676,518471,2020-03-17,15,373,コカ・コーラ1.5L,商品,1.0,149.0,1,大型PET__炭酸（大型PET）,434.0,0,4902102000468
10958677,518471,2020-03-17,15,379,豚挽肉（中）,商品,1.0,426.0,1,豚肉__挽肉,694.0,0,2528454000000
10958678,518471,2020-03-17,15,430,豚こま切れ（大）,商品,1.0,501.0,1,豚肉__こま切れ,687.0,0,2525527000000
10958679,518471,2020-03-17,15,505,プチチョコチップ,商品,1.0,68.0,1,チョコ・ビスクラ__ビスクラ,135.0,0,4901360312375
10958680,518471,2020-03-17,15,508,アポロ,商品,1.0,99.0,1,チョコ・ビスクラ__子供,136.0,0,45173639
10958681,518471,2020-03-17,15,537,混ぜ込みわかめ鮭,商品,1.0,99.0,1,調理品__ふりかけ・茶漬,663.0,0,4902820112412
10958682,518471,2020-03-17,15,541,のりたま 大袋,商品,1.0,179.0,1,調理品__ふりかけ・茶漬,663.0,0,4902820101126
10958683,518471,2020-03-17,15,665,若鶏むね肉１枚,商品,1.0,217.0,1,鶏肉__むね,753.0,0,2555403000000
10958684,518471,2020-03-17,15,835,香りソルトガーリック＆オ,商品,1.0,299.0,1,和風調味料__香辛料,390.0,0,49716221
10958685,518471,2020-03-17,15,898,味の素 袋,商品,1.0,159.0,1,和風調味料__塩,385.0,0,4901001283927
10958686,518471,2020-03-17,15,997,緑のたぬき天そば,商品,1.0,109.0,1,麺類__カップ麺,768.0,0,4901990527873
10958687,518471,2020-03-17,15,1181,おろし生にんにく,商品,1.0,89.0,1,和風調味料__香辛料,390.0,0,4902402653166
10958688,518471,2020-03-17,15,1249,大根,商品,1.0,99.0,1,野菜__根菜類,723.0,0,4522646735819
10958689,518471,2020-03-17,15,1331,人参袋,商品,1.0,129.0,1,野菜__根菜類,723.0,0,4935482121003
10958690,518471,2020-03-17,15,1529,トラウトサーモン刺身用ブ,商品,1.0,351.0,1,生魚__刺身ブロック,598.0,0,2513171000000
10958691,518471,2020-03-17,15,1658,エッセンシャルスマートリ,商品,1.0,349.0,1,ヘアケア__ヘアケア,188.0,0,4901301356796
10958692,518471,2020-03-17,15,1776,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN
10958693,518471,2020-03-17,15,1780,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN
10958694,518471,2020-03-17,15,1798,使用ポイント,確認,89.0,NaN,0,NaN,NaN,0,NaN
10958695,518471,2020-03-17,15,1819,通過ゲート,会計,NaN,NaN,0,NaN,NaN,1,NaN

In [49]:
log_df = pd.read_csv('../output/cart_log_re.csv')

qoupon_df = log_df[log_df['kind_1']=='クーポン'].groupby('session_id')[['kind_1']].count()
qoupon_df = pd.merge(qoupon_df, meta_df[['session_id', 'user_id']], on='session_id', how='left')
qoupon_df.columns = ['session_id', 'num_qoupon', 'user_id']
qoupon_df.head()

   session_id  num_qoupon                 user_id
0          63           1  4x6SEeZU89iakENbrPRr9Y
1         105           1  CN9sWHXp6RdCuyFkW5aemG
2         107           3  kTFrFDLeaaggCoubWZJHpg
3         108           2  exwdBc8tNJYAjhc4Gd6qtj
4         109           1  XUeiScqGsozKQFxcd3RDsD

In [50]:
qoupon_df.to_csv('../output/all_qoupon.csv', index=None)

In [51]:
pred_df = log_df[log_df.predict==0]

pred_qoupon_df = pred_df[pred_df['kind_1']=='クーポン'].groupby('session_id')[['kind_1']].count()
pred_qoupon_df = pd.merge(pred_qoupon_df, meta_df[['session_id', 'user_id']], on='session_id', how='left')
pred_qoupon_df.columns = ['session_id', 'num_qoupon', 'user_id']
pred_qoupon_df.head()

   session_id  num_qoupon                 user_id
0          63           1  4x6SEeZU89iakENbrPRr9Y
1         108           1  exwdBc8tNJYAjhc4Gd6qtj
2         109           1  XUeiScqGsozKQFxcd3RDsD
3         111           1  dmD9xugx2wQ5DWE4QUnKAX
4         113           2  9HHKE7g34AavgpjW65fDu4

In [52]:
pred_qoupon_df.to_csv('../output/given_qoupon.csv', index=None)

In [59]:
tmp = ['米飯(麺)__丼', '米飯(麺)__チルド米飯', 'たばこ__たばこその他', '和酒__清酒',
       '缶飲料__炭酸（缶・ボトル缶）', '米飯(麺)__原料・包材（米飯）', '水・炭酸水__小型PET（水）', '調理品__スープ・春雨', '乳製品__チーズ',
       'たばこ__輸入たばこ', 'デザート__要冷_洋生菓子', 'ハードリカー__スピリッツ',
       '調理家電__調理家電雑貨', '生活家電__生活家電雑貨', '生活家電__クリーナー', '健康・理美容家電__美容小物',
       'ハードリカー__ワイン','農産加工__水煮', '塩干(イン加工)__塩サバ', '塩干(イン加工)__干物', '冷凍__蒲焼・佃煮', '加工__冷凍(おかず)','塩干(イン加工)__鮭鱒', 
       '塩干(イン加工)__乾物', '塩干(イン加工)__漬魚', '生魚__魚惣菜', '温惣菜__コロッケ', '温惣菜__唐揚げ', '温惣菜__天ぷら', '温惣菜__フライカツ',
       '温惣菜__焼き物', '温惣菜__ＦＦ・甘味',
       '和菓子__半生・焼菓子', 'デザート__プリン', 'チョコ・ビスクラ__ビスクラ', 'デザート__ヨーグルト', '和菓子__季節(和菓子)',
       '和酒__焼酎', '調理品__和洋即席', '嗜好品__ジャム・蜂蜜',
       '衛生__ベビー用品', '珍味__珍味', '日配飲料__果汁・野菜', '乳製品__バター･マーガリン',
       'アイスクリーム__プレミアム', '麺類__パスタ', 'デザート__ゼリー', '和菓子__ゼリー','スナック・キャンディー__グミ', 'アイスクリーム__マルチ', '塩干__珍味', '塩干__魚卵',
       'スナック・キャンディー__キャンディ', '塩干__その他',
       '乳製品__ホイップ', '嗜好品__コーヒー・紅茶', '小型PET__無糖茶（小型PET）',
       '小型PET__炭酸（小型PET）',
       '調理素材__製菓材・デザート', '缶飲料__乳性（缶・ボトル缶）',
       'ハードリカー__洋酒', '冷惣菜__和惣菜',  '塩干__海藻', '塩干__ふりかけ', '塩干(イン加工)__珍味', '和洋菓子__洋菓子',
       'チョコ・ビスクラ__季節(洋菓子)', '調理品__フルーツ缶',
       '和洋菓子__和菓子', '冷凍食品__お弁当用', '冷凍食品__おかず', '和惣菜__チルド中華',
       '加工肉__お弁当', '加工肉__洋食', '塩干__小魚',
       '和日配__チルド麺', '麺類__乾麺・半生麺・棒麺',
       '農産加工__簡便野菜', '水・炭酸水__大型PET（水）',
       '珍味__豆菓子', '塩干__丸干し',
       'ホールセールパン__菓子パン(ホールセールパン)',
       '塩干__漬魚', 
       '加工肉__チルドソーセージ',
       '缶飲料__果汁（缶）', '缶飲料__紅茶（缶・ボトル缶）',
       '牛肉__挽肉', '米飯(麺)__弁当','ホールセールパン__食卓パン(ホールセールパン)',
       '小型PET__果汁（小型PET・ボトル缶）',
       '冷凍食品__麺類', '大型PET__紅茶（大型PET）',
       '水・炭酸水__缶・ボトル缶（水）',
       '米飯(麺)__おにぎり', '冷惣菜__レンジおかず', '冷惣菜__原料・包材（冷惣菜）',
       '塩干(イン加工)__季節商材',
       '羊・馬肉__ステーキ', '塩干__季節商材', 'サンド__サンド', 'ピザ__原料・包材(ピザ)',
       'サンド__OUTサンド', 'ピザ__クラスト', 'サンド__原料・包材(サンド)',
       '米飯(麺)__外食', 'サンド__サンドその他',
       'ピザ__冷凍', '明治屋テナント__ワイルドビーフ', '明治屋テナント__明治軒', '明治屋テナント__麺や天吉',
       'ピザ__チルド', '加工__おつまみ(セット）', '塩干__干物', '加工肉__ハム・ベーコン', '冷凍食品__スナック',
       '冷凍食品__米飯', '麺類__袋麺', 'キッチン__焼物・揚物',
       '缶飲料__嗜好性飲料（缶・ボトル缶）', '小型PET__紅茶（小型PET）',
       '大型PET__果汁（大型PET）', '缶飲料__スポーツ・機能性（缶・ボトル缶）',
       '大型PET__スポーツ・機能性（大型PET）', '小型PET__乳性（小型PET）', '大型PET__乳性（大型PET）',
       '缶飲料__コーヒー（ボトル缶）', '小型PET__嗜好性飲料（小型PET）', '調理家電__コーヒーメーカー',
       '珍味__小袋', '塩干__鮭鱒',
       'ホールセールパン__食パン(ホールセールパン)',
       'ホールセールパン__惣菜パン(ホールセールパン)', 'ホールセールパン__調理パン', '冷凍食品__パスタ麺',
       '加工肉__おかず',
       'ホールセールパン__携帯型サンドイッチ', '100円均一__食品',]

In [60]:
len(tmp)

137